### ISSUE TITLE
数据在哪里下载？

### ISSUE THREAD

**Issue by liuyan-design** [qlwang25/multi-perspectives_example_retrieval#1]

**Comment by qlwang25** [comment]
you can download dataset according to paper:
1. `MEMD-ABSA: A Multi-Element Multi-Domain Dataset for Aspect-Based Sentiment Analysis`
2. `Semeval-2014 task 4: Aspect based sentiment analysis`

**Comment by Cai-dashuang** [comment]
Hello, what format does the data need to be processed into？

**Comment by Cai-dashuang** [comment]
tokens and tags mean what they mean ？

**Comment by 1259927114** [comment]
> tokens and tags mean what they mean ？

Hello, have you resolved this issue now? I have the same confusion/question.
